spring:
  datasource:
    url: jdbc:mysql://localhost:3306/serverdb
    username: root
    password: SQLhmtgl@467
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
      format-sql: true
